FROM node:latest

WORKDIR /app/medusa

COPY . .

RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3

RUN npm global add @medusajs/medusa-cli

RUN npm

RUN npm build

CMD medusa migrations run && npm start